/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.ethz.bsse.indelfixer;

import ch.ethz.bsse.indelfixer.stored.Globals;
import jaligner.Alignment;
import jaligner.Sequence;
import jaligner.SmithWatermanGotoh;
import jaligner.matrix.MatrixLoader;
import jaligner.matrix.MatrixLoaderException;
import java.util.logging.Logger;
import org.junit.*;

/**
 *
 * @author toepfera
 */
public class ReadTest {
    
    /**
     *
     */
    public ReadTest() {
        Globals.KMER_LENGTH = 5;
    }

    /**
     * Test of getKmers method, of class Read.
     */
    @Test
    public void testGetKmers() throws MatrixLoaderException {
        String genome = "CCTCTGATCACTCTTTGGCAGCGACCCCTCGTCACAATAAAGATAGGGGGGCAACTAAAGGAAGCTCTATTAGATACAGGAGCAGATGATACAGTGTTAGAAGAAATGAATTTACCAGGAAGATGGAAACCAAAAATGATAGGGGGAATTGGAGGTTTTATCAAAGTAAGACAGTATGATCAGATACCCATAGAAGTTTGTGGACATAAAGCTATAGGTACAGTATTAGTAGGACCTACACCTGTCAACATAATTGGAAGGAATCTGTTGACCGAGATTGGTTGCACTTTAAATTTTCCCATTAGTCCTATTGAAACTGTACCAGTAAAATTAAAGCCGGGAATGGATGGCCCAAAGGTTAAACAATGGCCATTGACAGAAGAAAAAATAAAAGCATTAGTAGAAATTTGTACTGAAATGGAAAAGGAGGGGAAAATTTCAAAAATTGGACCTGAAAATCCATACAATACTCCAATATTTGCCATAAAGAAAAAAGATGGGACTAAATGGAGAAAATTAGTGGATTTCAGAGAACTTAATAAAAGAACTCAAGACTTCTGGGAAGTTCAGTTAGGAATACCCCATCCCGCAGGGTTTAAAAAGAAAAAATCAATAACAGTACTGGATGTGGGTGATGCGTATTTTTCAGTTCCCTTAGATGAAGACTTCAGGAAGTATACTGCATTCACCATACCTAGTATAAACAATGAGACACCAGGAATTAGATATCAGTACAATGTGCTTCCACAAGGACGGAAAGGATCACCAGCAATATTCCAAAGTAGCATGACAAAAATCTTAGAGCCTTTTAGAAAACAAAGTCCAGACATAGTTATCTATCAGTACATGGATGACTTGTATGTAGGATCTGACTTAGAAATAGGGCAGCATAGAATAAAAATAGAAGAACTGAGGCAGCATCTGTTGCAGTGGGGATTTACCACACCAGACAAAAAACATCAGAAAGAACCTCCATTCCTTTGGATGGGTTATGAACTCCATCCTGATAAATGGACAGTACAGCCTATAGAGCTGCCAGAAAAAGATAGCTGGACTGTCAATGACATACAGAAGTTAGTGGGAAAATTAAATTGGGCAAGTCAAATTTATCCAGGGATTAAAGTAAGGCAATTATGTAAGCCCCTTAGGGGAACCAAAGCACTAACAGAAATAATACCACTAACAGAAGAAGCGGAGCTAGAACTAGCAGAAAACAGGGAGATTTTAAAAGAATCAGTACATGGA";
        Alignment align = SmithWatermanGotoh.align(
                                                  new Sequence(genome.substring(0, 1_000), "", "", Sequence.NUCLEIC),
                                                  new Sequence("TGATGCGTATTTTTCAGTTCCCTTAGATGAAGACTTCAGGAAGTATACTGCATTCACCATACCTAGTATAAACAATGAGACACCAGGAATTAGATATCAGTACAATGTGCTTCCACAAGGACGGAAAGGATCACCAGCAATATTCCAAAG", "", "", Sequence.NUCLEIC),
//                                                  new Sequence("ACTCTTTGGCAGCGACCCCTCGTCACAATAAAGATAGGGGGGCAACTAAAGGAAGCTCTATTAGATACAGGAGCAGATGATACAGTGTTAGAAGAAATGAATTTACCAGGAAGATGGAAACCAAAAATGATAGGGGGAATTGGAGGTTTT", "", "", Sequence.NUCLEIC),
                                                  MatrixLoader.load("EDNAFULL"), 10, 1);
    }
    private static final Logger LOG = Logger.getLogger(ReadTest.class.getName());
}
